@extends('layouts.app')
@section('title', 'Remuneraciones')
@section('content')
@php
    use App\Support\Duration;
    use App\Support\Money;
@endphp
<div class="mx-auto max-w-6xl space-y-6">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
        <div><p class="text-sm font-semibold uppercase tracking-wider text-amber-600">Etapa 9</p><h1 class="mt-2 text-3xl font-bold">Cálculo de remuneraciones</h1><p class="mt-2 text-sm text-slate-600">Resultados mensuales basados exclusivamente en el cálculo de horas cerrado.</p></div>
        @if($selectedPeriod)<form method="POST" action="{{ route('remunerations.store', $selectedPeriod) }}">@csrf<button class="button-primary">{{ $activeCalculations->contains(fn ($item) => $item->remuneration) ? 'Recalcular remuneraciones' : 'Calcular remuneraciones' }}</button></form>@endif
    </div>
    <nav aria-label="Ruta de navegación" class="flex flex-wrap items-center gap-1 rounded-xl border border-slate-200 bg-white p-2 shadow-sm"><a href="{{ route('remunerations.index') }}" class="rounded-lg px-3 py-2 font-semibold text-slate-700 hover:bg-slate-100">Períodos</a>@if($selectedPeriod)<span class="text-slate-400">›</span><a href="{{ route('remunerations.index', ['control_period_id' => $selectedPeriod->id]) }}" class="rounded-lg px-3 py-2 font-semibold text-slate-700 hover:bg-slate-100">{{ $selectedPeriod->name }}</a>@endif @if($selectedCalculation)<span class="text-slate-400">›</span><span class="px-3 py-2 font-semibold text-slate-500">{{ $selectedCalculation->collaborator?->full_name ?? $selectedCalculation->person->source_name }}</span>@endif</nav>

    @if(!$selectedPeriod)
        <section><h2 class="text-xl font-semibold">Selecciona un período</h2><div class="mt-4 grid gap-4 md:grid-cols-2">@forelse($periods as $period)@php($summary = $periodSummaries[$period->id])<a href="{{ route('remunerations.index', ['control_period_id' => $period->id]) }}" class="card block transition hover:border-slate-400"><div class="flex items-center justify-between"><span class="text-xl font-bold">{{ $period->name }}</span><span class="text-2xl">›</span></div><div class="mt-4 space-y-1.5 text-sm">@if($summary['calculated'])<p><span class="font-semibold">{{ $summary['calculated'] }}</span> calculadas</p>@endif @if($summary['blocked'])<p><span class="font-semibold">{{ $summary['blocked'] }}</span> requieren revisión</p>@endif @if($summary['configuration_pending'])<p><span class="font-semibold">{{ $summary['configuration_pending'] }}</span> con configuración pendiente</p>@endif @if($summary['stale'])<p><span class="font-semibold">{{ $summary['stale'] }}</span> requieren recálculo</p>@endif @if($summary['not_calculated'])<p><span class="font-semibold">{{ $summary['not_calculated'] }}</span> pendientes de cálculo</p>@endif @if(!$summary['calculated'] && !$summary['blocked'] && !$summary['configuration_pending'] && !$summary['stale'] && !$summary['not_calculated'])<p class="font-semibold text-slate-500">Remuneraciones pendientes de cálculo</p>@endif @if($summary['without_marks'])<p class="text-slate-500">{{ $summary['without_marks'] }} sin marcaciones</p>@endif</div></a>@empty<div class="card text-center text-slate-500 md:col-span-2">Primero debes calcular las horas de un período.</div>@endforelse</div></section>
    @elseif(!$selectedCalculation)
        <section><h2 class="text-xl font-semibold">Colaboradores con actividad</h2><p class="mt-1 text-sm text-slate-500">El cálculo es explícito y se bloquea cuando existen jornadas pendientes.</p><div class="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            @foreach($activeCalculations as $calculation)
                @php($remuneration = $calculation->remuneration)
                <a href="{{ route('remunerations.index', ['control_period_id' => $selectedPeriod->id, 'calculation_id' => $calculation->id]) }}" class="card block transition hover:border-slate-400"><h3 class="font-bold">{{ $calculation->collaborator?->full_name ?? $calculation->person->source_name }}</h3>@if(!$remuneration)<p class="mt-2 text-sm font-semibold text-slate-500">Pendiente de cálculo</p>@elseif($calculation->remuneration_is_stale)<p class="mt-2 text-sm font-semibold text-amber-700">Requiere recálculo</p><p class="text-xs text-slate-500">El importe anterior ya no está vigente.</p>@elseif($remuneration->status === 'calculated')<p class="mt-2 text-lg font-bold text-emerald-700">{{ Money::human($remuneration->final_amount_cents) }}</p><p class="text-xs text-slate-500">Calculada</p>@elseif($remuneration->status === 'blocked')<p class="mt-2 text-sm font-semibold text-amber-700">Pendiente de cierre</p>@else<p class="mt-2 text-sm font-semibold text-amber-700">Configuración pendiente</p>@endif</a>
            @endforeach
        </div>@if($withoutMarksCalculations->isNotEmpty())<details class="card mt-5"><summary class="cursor-pointer font-semibold">Ver colaboradores sin marcaciones ({{ $withoutMarksCalculations->count() }})</summary><div class="mt-4 grid gap-3 sm:grid-cols-2">@foreach($withoutMarksCalculations as $calculation)<div class="rounded-xl border border-slate-200 p-4"><p class="font-semibold">{{ $calculation->collaborator?->full_name ?? $calculation->person->source_name }}</p><p class="text-sm text-slate-500">Sin marcaciones · no genera remuneración</p></div>@endforeach</div></details>@endif</section>
    @else
        @php($remuneration = $selectedCalculation->remuneration)
        <section class="space-y-5">
            <div class="card">
                <div class="flex flex-wrap items-start justify-between gap-3"><div><h2 class="text-2xl font-bold">{{ $selectedCalculation->collaborator?->full_name ?? $selectedCalculation->person->source_name }}</h2><p class="text-sm text-slate-500">{{ $selectedPeriod->name }}</p></div><span class="rounded-full px-3 py-1 text-sm font-semibold {{ $remuneration?->status === 'calculated' && !$isStale ? 'bg-emerald-100 text-emerald-800' : 'bg-amber-100 text-amber-900' }}">{{ !$remuneration ? 'Pendiente' : ($isStale ? 'Requiere recálculo' : ['calculated' => 'Calculada', 'blocked' => 'Pendiente de cierre', 'configuration_pending' => 'Configuración pendiente'][$remuneration->status]) }}</span></div>
                @if(!$remuneration)<p class="mt-5 rounded-xl bg-slate-50 p-4 text-sm">La remuneración todavía no fue calculada. Usa la acción “Calcular remuneraciones”.</p>
                @elseif($remuneration->status === 'blocked')<div class="mt-5 rounded-xl bg-amber-50 p-4 text-amber-900"><p class="font-semibold">Remuneración pendiente de cierre</p><p class="mt-1 text-sm">Existen {{ $selectedCalculation->pending_days }} jornadas que requieren revisión antes de calcular la remuneración.</p><a class="mt-3 inline-block text-sm font-semibold underline" href="{{ route('attendance-corrections.index', ['control_period_id' => $selectedPeriod->id, 'person_id' => $selectedCalculation->biometric_import_person_id]) }}">Resolver inconsistencias</a></div>
                @elseif($remuneration->status === 'configuration_pending')<p class="mt-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-900">No existe una única condición laboral válida para este período. Corrige la condición y recalcula explícitamente.</p>
                @else
                    @if($isStale)<p class="mt-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-900"><strong>Resultado desactualizado:</strong> cambiaron las horas, los días de referencia o la condición laboral. El importe anterior se conserva internamente, pero ya no se presenta como remuneración vigente. Ejecuta “Recalcular remuneraciones”.</p>@else
                    <dl class="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                        <div><dt class="text-sm text-slate-500">Salario mensual base</dt><dd class="mt-1 text-xl font-bold">{{ Money::human($remuneration->base_amount_cents) }}</dd></div>
                        <div><dt class="text-sm text-slate-500">Horas semanales</dt><dd class="mt-1 text-xl font-bold">{{ number_format($remuneration->weekly_hours_hundredths / 100, 2, ',', '.') }} h</dd></div>
                        <div><dt class="text-sm text-slate-500">Horas diarias de referencia</dt><dd class="mt-1 text-xl font-bold">{{ rtrim(rtrim(number_format((float) $remuneration->daily_reference_hours, 6, ',', ''), '0'), ',') }} h</dd></div>
                        <div><dt class="text-sm text-slate-500">Días de referencia</dt><dd class="mt-1 text-xl font-bold">{{ $remuneration->reference_days }}</dd></div>
                        <div><dt class="text-sm text-slate-500">Horas esperadas</dt><dd class="mt-1 font-bold">{{ Duration::human($remuneration->expected_minutes) }}</dd></div>
                        <div><dt class="text-sm text-slate-500">Horas reconocidas</dt><dd class="mt-1 font-bold">{{ Duration::human($remuneration->recognized_minutes) }}</dd></div>
                        <div><dt class="text-sm text-slate-500">{{ $remuneration->deficit_minutes ? 'Déficit' : ($remuneration->surplus_minutes ? 'Excedente' : 'Diferencia') }}</dt><dd class="mt-1 font-bold">{{ Duration::human($remuneration->difference_minutes, true) }}</dd></div>
                        <div><dt class="text-sm text-slate-500">Tarifa horaria</dt><dd class="mt-1 font-bold">Bs {{ number_format((float) $remuneration->hourly_rate, 10, ',', '.') }}/h</dd></div>
                    </dl>
                    <div class="mt-6 rounded-2xl bg-slate-950 p-5 text-white"><div class="space-y-2 text-sm"><p class="flex justify-between"><span>Remuneración base</span><strong>{{ Money::human($remuneration->base_amount_cents) }}</strong></p>@if($remuneration->deficit_minutes)<p class="flex justify-between text-red-300"><span>Deducción por déficit ({{ intdiv($remuneration->valued_duration_hundredths, 100) }}.{{ str_pad((string) ($remuneration->valued_duration_hundredths % 100), 2, '0', STR_PAD_LEFT) }})</span><strong>−{{ Money::human($remuneration->deficit_deduction_cents) }}</strong></p>@endif @if($remuneration->surplus_minutes)<p class="flex justify-between text-emerald-300"><span>Incremento por excedente ({{ intdiv($remuneration->valued_duration_hundredths, 100) }}.{{ str_pad((string) ($remuneration->valued_duration_hundredths % 100), 2, '0', STR_PAD_LEFT) }})</span><strong>+{{ Money::human($remuneration->surplus_increment_cents) }}</strong></p>@endif</div><div class="mt-4 flex items-end justify-between border-t border-white/20 pt-4"><span class="font-semibold">Remuneración final</span><strong class="text-3xl">{{ Money::human($remuneration->final_amount_cents) }}</strong></div><p class="mt-3 text-xs text-slate-300">Tarifa calculada sin redondeo previo. Solamente el ajuste monetario final se redondea a dos decimales.</p></div>
                    <p class="mt-4 text-xs text-slate-500">Condición laboral #{{ $remuneration->employment_condition_id }} · Calculado {{ $remuneration->calculated_at->format('d/m/Y H:i') }}</p>
                    @endif
                @endif
            </div>
            <div><h3 class="text-xl font-semibold">Trazabilidad diaria</h3><p class="mt-1 text-sm text-slate-500">Las jornadas explican las horas del período; no se calculan salarios diarios independientes.</p><div class="card mt-4 overflow-x-auto p-3"><div class="min-w-[38rem]"><div class="grid grid-cols-7 gap-1 text-center text-xs font-semibold uppercase text-slate-500">@foreach(['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'] as $weekday)<div class="py-2">{{ $weekday }}</div>@endforeach</div><div class="space-y-1">
                @foreach($calendarWeeks as $week)<div class="grid grid-cols-7 gap-1">@foreach($week as $cell)
                    @if(!$cell)<div class="min-h-24 rounded-xl bg-slate-50"></div>
                    @else
                        @php($day = $cell['data'])
                        @php($state = !$day || $day->status === 'no_marks' ? 'none' : ($day->status === 'pending' ? 'pending' : ($day->source_type === 'correction' ? 'corrected' : 'recognized')))
                        @php($classes = ['none'=>'border-slate-100 bg-slate-50 text-slate-500','pending'=>'border-amber-300 bg-amber-50 text-amber-900','corrected'=>'border-blue-300 bg-blue-50 text-blue-900','recognized'=>'border-emerald-300 bg-emerald-50 text-emerald-900'][$state])
                        @php($stateLabel = ['none'=>'Sin marcaciones','pending'=>'Requiere revisión','corrected'=>'Corregida','recognized'=>'Compatible'][$state])
                        @if(in_array($state, ['corrected', 'recognized'], true))
                            <button type="button" data-calculation-day-open data-source="remuneration-day-{{ $day->id }}" class="min-h-24 rounded-xl border p-2 text-left {{ $classes }}"><span class="text-xl font-bold">{{ $cell['day'] }}</span><span class="mt-2 block text-xs font-semibold">{{ $stateLabel }}</span><span class="mt-2 block text-xs font-bold">{{ Duration::human($day->recognized_minutes) }}</span></button>
                            <template id="remuneration-day-{{ $day->id }}"><div><p class="text-sm font-semibold uppercase tracking-wide text-amber-600">Trazabilidad de jornada</p><h2 class="mt-1 text-xl font-bold">{{ $day->work_date->locale('es')->translatedFormat('j \d\e F \d\e Y') }}</h2><div class="mt-5 space-y-3">@foreach($day->intervals as $interval)<div class="rounded-xl bg-slate-50 p-3"><p class="font-semibold">{{ $interval->started_at->format('H:i') }} → {{ $interval->ended_at->format('H:i') }}</p><p class="text-sm text-slate-600">{{ Duration::human($interval->minutes) }}</p></div>@endforeach</div><div class="mt-5 border-t pt-4"><p class="text-sm text-slate-500">Total reconocido</p><p class="text-2xl font-bold">{{ Duration::human($day->recognized_minutes) }}</p><p class="mt-3 text-sm font-semibold">{{ $stateLabel }}</p>@if($remuneration?->status === 'calculated' && !$isStale)<p class="mt-4 rounded-xl bg-blue-50 p-3 text-sm text-blue-900">Esta jornada integra el total mensual. Tarifa de referencia: Bs {{ number_format((float) $remuneration->hourly_rate, 10, ',', '.') }}/h. La remuneración se determina a nivel del período.</p>@endif</div></div></template>
                        @elseif($state === 'pending')<a href="{{ route('attendance-corrections.index', ['control_period_id' => $selectedPeriod->id, 'person_id' => $selectedCalculation->biometric_import_person_id, 'interpretation_id' => $day->attendance_interpretation_id]) }}" class="min-h-24 rounded-xl border p-2 {{ $classes }}"><span class="text-xl font-bold">{{ $cell['day'] }}</span><span class="mt-2 block text-xs font-semibold">{{ $stateLabel }}</span></a>
                        @else<div class="min-h-24 rounded-xl border p-2 {{ $classes }}"><span class="text-xl font-bold">{{ $cell['day'] }}</span><span class="mt-2 block text-xs font-semibold">{{ $stateLabel }}</span></div>@endif
                    @endif
                @endforeach</div>@endforeach
            </div></div></div></div>
        </section>
    @endif
</div>
<dialog id="calculation-day-modal" class="fixed inset-0 m-auto max-h-[92vh] w-[min(34rem,calc(100%-1rem))] overflow-y-auto rounded-2xl bg-white p-0 shadow-2xl backdrop:bg-slate-950/60"><div class="p-5 sm:p-7"><div class="flex justify-end"><button type="button" data-modal-close aria-label="Cerrar" class="rounded-lg px-3 py-1 text-2xl text-slate-500 hover:bg-slate-100">×</button></div><div data-calculation-day-content></div></div></dialog>
@endsection
