@php($resolvedConditionAction = $conditionAction ?? (old('condition_collaborator_id') ? route('collaborators.conditions.store', old('condition_collaborator_id')) : ''))
<dialog id="condition-modal" @if($errors->hasAny(['job_role_id', 'weekly_hours', 'monthly_salary', 'effective_from', 'effective_to', 'reason'])) data-open-on-errors @endif class="fixed inset-0 m-auto max-h-[90vh] w-[min(44rem,calc(100%-2rem))] overflow-y-auto rounded-2xl bg-white p-0 shadow-2xl backdrop:bg-slate-950/60">
    <div class="p-5 sm:p-7">
        <div class="flex items-start justify-between gap-4"><div><p class="text-sm font-semibold uppercase tracking-wide text-amber-600">Condición laboral</p><h2 class="mt-1 text-xl font-bold">Nueva condición <span data-condition-person></span></h2><p class="mt-2 text-sm text-slate-500">El acuerdo anterior se conservará en el historial.</p></div><button type="button" data-modal-close aria-label="Cerrar" class="rounded-lg px-3 py-1 text-2xl text-slate-500 hover:bg-slate-100">×</button></div>
        <form data-condition-form method="POST" action="{{ $resolvedConditionAction }}" class="mt-6 grid gap-4 sm:grid-cols-2">@csrf<input data-condition-collaborator type="hidden" name="condition_collaborator_id" value="{{ old('condition_collaborator_id') }}">
            <div class="sm:col-span-2"><label for="job_role_id" class="mb-2 block text-sm font-medium">Rol laboral <span class="text-red-600">*</span></label><select id="job_role_id" name="job_role_id" required class="field @error('job_role_id') field-error @enderror"><option value="">Selecciona un rol</option>@foreach($jobRoles as $jobRole)<option value="{{ $jobRole->id }}" data-reference-hours="{{ $jobRole->reference_weekly_hours }}" data-reference-salary="{{ $jobRole->reference_monthly_salary }}" @selected((string) old('job_role_id', $currentCondition?->job_role_id ?? null) === (string) $jobRole->id)>{{ $jobRole->name }}</option>@endforeach</select>@error('job_role_id')<p class="field-message">{{ $message }}</p>@enderror</div>
            <div><label for="weekly_hours" class="mb-2 block text-sm font-medium">Horas semanales <span class="text-red-600">*</span></label><input id="weekly_hours" name="weekly_hours" type="number" min="0.01" max="168" step="0.01" value="{{ old('weekly_hours') }}" required class="field @error('weekly_hours') field-error @enderror">@error('weekly_hours')<p class="field-message">{{ $message }}</p>@enderror</div>
            <div><label for="monthly_salary" class="mb-2 block text-sm font-medium">Salario mensual acordado (Bs.) <span class="text-red-600">*</span></label><input id="monthly_salary" name="monthly_salary" type="number" min="0.01" step="0.01" value="{{ old('monthly_salary') }}" required class="field @error('monthly_salary') field-error @enderror"><p id="suggested-monthly-salary" class="mt-1 text-xs text-slate-500">Se sugerirá un valor según el rol y las horas.</p>@error('monthly_salary')<p class="field-message">{{ $message }}</p>@enderror</div>
            <div><label for="effective_from" class="mb-2 block text-sm font-medium">Inicio de vigencia <span class="text-red-600">*</span></label><input id="effective_from" name="effective_from" type="date" value="{{ old('effective_from', today()->toDateString()) }}" required class="field @error('effective_from') field-error @enderror">@error('effective_from')<p class="field-message">{{ $message }}</p>@enderror</div>
            <div><label for="effective_to" class="mb-2 block text-sm font-medium">Fin de vigencia <span class="text-slate-400">(opcional)</span></label><input id="effective_to" name="effective_to" type="date" value="{{ old('effective_to') }}" class="field @error('effective_to') field-error @enderror">@error('effective_to')<p class="field-message">{{ $message }}</p>@enderror</div>
            <div class="sm:col-span-2"><label for="reason" class="mb-2 block text-sm font-medium">Motivo <span class="text-slate-400">(opcional)</span></label><input id="reason" name="reason" type="text" value="{{ old('reason') }}" class="field @error('reason') field-error @enderror">@error('reason')<p class="field-message">{{ $message }}</p>@enderror</div>
            <div class="sm:col-span-2 flex flex-col-reverse gap-3 border-t border-slate-200 pt-5 sm:flex-row sm:justify-end"><button type="button" data-modal-close class="button-secondary">Cancelar</button><button type="submit" class="button-primary">Registrar condición</button></div>
        </form>
    </div>
</dialog>
