@php($editing = isset($collaborator))

<div class="space-y-7">
    <section>
        <h2 class="text-lg font-semibold">Datos del colaborador</h2>
        <p class="mt-1 text-sm text-slate-500">Información principal para identificar su registro.</p>
        <div class="mt-5 grid gap-5 sm:grid-cols-2">
            <div><label for="full_name" class="mb-2 block text-sm font-medium">Nombre completo <span class="text-red-600">*</span></label><input id="full_name" name="full_name" type="text" value="{{ old('full_name', $collaborator->full_name ?? '') }}" required class="field @error('full_name') field-error @enderror">@error('full_name')<p class="field-message">{{ $message }}</p>@enderror</div>
            <div><label for="biometric_id" class="mb-2 block text-sm font-medium">ID biométrico <span class="text-red-600">*</span></label><input id="biometric_id" name="biometric_id" type="number" min="1" value="{{ old('biometric_id', $collaborator->biometric_id ?? '') }}" required class="field @error('biometric_id') field-error @enderror"><p class="mt-1.5 text-xs text-slate-500">Identificador asignado en el dispositivo biométrico.</p>@error('biometric_id')<p class="field-message">{{ $message }}</p>@enderror</div>
            <div><label for="hire_date" class="mb-2 block text-sm font-medium">Fecha de ingreso <span class="text-red-600">*</span></label><input id="hire_date" name="hire_date" type="date" max="{{ today()->toDateString() }}" value="{{ old('hire_date', isset($collaborator) ? $collaborator->hire_date->toDateString() : today()->toDateString()) }}" required class="field @error('hire_date') field-error @enderror">@error('hire_date')<p class="field-message">{{ $message }}</p>@enderror</div>
            <div><label for="occupation_status" class="mb-2 block text-sm font-medium">Situación ocupacional <span class="text-slate-400">(opcional)</span></label><select id="occupation_status" name="occupation_status" class="field @error('occupation_status') field-error @enderror"><option value="">Sin especificar</option><option value="student" @selected(old('occupation_status', $collaborator->occupation_status ?? '') === 'student')>Estudiante</option><option value="full_time" @selected(old('occupation_status', $collaborator->occupation_status ?? '') === 'full_time')>Jornada completa</option><option value="part_time" @selected(old('occupation_status', $collaborator->occupation_status ?? '') === 'part_time')>Jornada parcial</option></select>@error('occupation_status')<p class="field-message">{{ $message }}</p>@enderror</div>
            <div class="sm:col-span-2"><label for="notes" class="mb-2 block text-sm font-medium">Observaciones <span class="text-slate-400">(opcional)</span></label><textarea id="notes" name="notes" rows="3" class="field @error('notes') field-error @enderror">{{ old('notes', $collaborator->notes ?? '') }}</textarea>@error('notes')<p class="field-message">{{ $message }}</p>@enderror</div>
        </div>
    </section>

    @unless($editing)
        <section class="border-t border-slate-200 pt-7">
            <h2 class="text-lg font-semibold">Información laboral</h2>
            <p class="mt-1 text-sm text-slate-500">Selecciona el compromiso semanal y el rol para obtener una referencia económica.</p>
            <div class="mt-5 grid gap-5 sm:grid-cols-2">
                <div><label for="weekly_hours" class="mb-2 block text-sm font-medium">Horas semanales comprometidas <span class="text-red-600">*</span></label><input id="weekly_hours" name="weekly_hours" type="number" min="0.01" max="168" step="0.01" value="{{ old('weekly_hours') }}" required class="field @error('weekly_hours') field-error @enderror">@error('weekly_hours')<p class="field-message">{{ $message }}</p>@enderror</div>
                <div><label for="job_role_id" class="mb-2 block text-sm font-medium">Rol laboral <span class="text-red-600">*</span></label><select id="job_role_id" name="job_role_id" required class="field @error('job_role_id') field-error @enderror"><option value="">Selecciona un rol</option>@foreach($jobRoles as $jobRole)<option value="{{ $jobRole->id }}" data-reference-hours="{{ $jobRole->reference_weekly_hours }}" data-reference-salary="{{ $jobRole->reference_monthly_salary }}" @selected((string) old('job_role_id') === (string) $jobRole->id)>{{ $jobRole->name }}</option>@endforeach</select>@error('job_role_id')<p class="field-message">{{ $message }}</p>@enderror</div>
                <div class="sm:col-span-2 rounded-xl border border-amber-200 bg-amber-50 p-4"><p class="text-xs font-semibold uppercase tracking-wide text-amber-700">Salario mensual estimado</p><p id="estimated-salary" class="mt-1 text-xl font-bold text-slate-900">Selecciona un rol e indica las horas</p><p class="mt-1 text-xs text-slate-600">Sugerencia proporcional; puedes modificar libremente el salario acordado.</p></div>
            </div>
        </section>

        <section class="border-t border-slate-200 pt-7">
            <h2 class="text-lg font-semibold">Condición laboral inicial</h2>
            <p class="mt-1 text-sm text-slate-500">Define el acuerdo y sus fechas de vigencia.</p>
            <div class="mt-5 grid gap-5 md:grid-cols-3">
                <div><label for="monthly_salary" class="mb-2 block text-sm font-medium">Salario mensual acordado (Bs.) <span class="text-red-600">*</span></label><input id="monthly_salary" name="monthly_salary" type="number" min="0.01" step="0.01" value="{{ old('monthly_salary') }}" required class="field @error('monthly_salary') field-error @enderror">@error('monthly_salary')<p class="field-message">{{ $message }}</p>@enderror</div>
                <div><label for="effective_from" class="mb-2 block text-sm font-medium">Inicio de vigencia <span class="text-red-600">*</span></label><input id="effective_from" name="effective_from" type="date" value="{{ old('effective_from', today()->toDateString()) }}" required class="field @error('effective_from') field-error @enderror">@error('effective_from')<p class="field-message">{{ $message }}</p>@enderror</div>
                <div><label for="effective_to" class="mb-2 block text-sm font-medium">Fin de vigencia <span class="text-slate-400">(opcional)</span></label><input id="effective_to" name="effective_to" type="date" value="{{ old('effective_to') }}" class="field @error('effective_to') field-error @enderror">@error('effective_to')<p class="field-message">{{ $message }}</p>@enderror</div>
                <div class="md:col-span-3"><label for="condition_reason" class="mb-2 block text-sm font-medium">Motivo <span class="text-slate-400">(opcional)</span></label><input id="condition_reason" name="condition_reason" type="text" value="{{ old('condition_reason') }}" placeholder="Ej.: horario reducido por semestre académico" class="field @error('condition_reason') field-error @enderror">@error('condition_reason')<p class="field-message">{{ $message }}</p>@enderror</div>
            </div>
            <input type="hidden" name="is_active" value="1">
        </section>
    @endunless

    <details class="group border-t border-slate-200 pt-7">
        <summary class="flex cursor-pointer list-none items-center justify-between rounded-xl bg-slate-50 px-4 py-3 font-semibold"><span>Identificación y contacto <span class="text-sm font-normal text-slate-500">(opcional)</span></span><span class="text-xl transition group-open:rotate-45">+</span></summary>
        <div class="mt-5 grid gap-5 sm:grid-cols-2"><div><label for="identity_document" class="mb-2 block text-sm font-medium">Documento de identidad <span class="text-slate-400">(opcional)</span></label><input id="identity_document" name="identity_document" type="text" value="{{ old('identity_document', $collaborator->identity_document ?? '') }}" class="field @error('identity_document') field-error @enderror">@error('identity_document')<p class="field-message">{{ $message }}</p>@enderror</div><div><label for="phone" class="mb-2 block text-sm font-medium">Teléfono <span class="text-slate-400">(opcional)</span></label><input id="phone" name="phone" type="text" value="{{ old('phone', $collaborator->phone ?? '') }}" class="field @error('phone') field-error @enderror">@error('phone')<p class="field-message">{{ $message }}</p>@enderror</div><div><label for="email" class="mb-2 block text-sm font-medium">Correo electrónico <span class="text-slate-400">(opcional)</span></label><input id="email" name="email" type="email" value="{{ old('email', $collaborator->email ?? '') }}" class="field @error('email') field-error @enderror">@error('email')<p class="field-message">{{ $message }}</p>@enderror</div><div><label for="address" class="mb-2 block text-sm font-medium">Dirección <span class="text-slate-400">(opcional)</span></label><input id="address" name="address" type="text" value="{{ old('address', $collaborator->address ?? '') }}" class="field @error('address') field-error @enderror">@error('address')<p class="field-message">{{ $message }}</p>@enderror</div></div>
    </details>
</div>

<div class="mt-8 flex flex-col-reverse gap-3 border-t border-slate-200 pt-6 sm:flex-row sm:justify-end"><a href="{{ $editing ? route('collaborators.show', $collaborator) : route('collaborators.index') }}" class="button-secondary">Cancelar</a><button type="submit" class="button-primary">{{ $editing ? 'Guardar cambios' : 'Crear colaborador' }}</button></div>
